title: uBuild Design Blocks
author: creatorkorxx
email: creatorkorxx@gmail.com
description: >-

baseurl: ""
url: "https://dd-kor.github.io/"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

